config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] do
    # profile/ user page
    member do
      get :posts
      get :replies
      get :collects
      get :drafts
      get :friends
    end
  end

  root "posts#index" 
  resources :posts do
    resources :replies, only: [:create, :destroy, :edit, :update]
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  resources :friendships, only: [:create, :destroy] do
    member do
      patch :ignore
      patch :connect
    end
  end

  resources :categories, only: :show

  namespace :admin do
    resources :categories
    resources :users, only: [:index, :update]
    root "users#index"
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PhotoUploader
  
  # validates_presence_of :title, :description
  validates_inclusion_of :permit, :in => ["all", "friend", "myself"]
  validates_inclusion_of :status, :in => ["publish", "draft"]

  belongs_to :user

  has_many :category_of_posts, dependent: :destroy
  has_many :categories, through: :category_of_posts

  has_many :replies, dependent: :destroy

  has_many :vieweds, dependent: :destroy

  has_many :collects, dependent: :destroy
  has_many :collected_users, through: :collects, source: :user

  def self.all_publish(user)  # 原本版本有衝突
    where( :status => 'publish', :permit => 'all')
  end

  def self.publishs
    where( :status => 'publish').all
  end 

  def self.drafts
    where( :status => 'draft').all
  end

  def collected? (user)
    self.collected_users.include?(user)
  end

  def last_replied_at
    self.replies.first.created_at.to_date
  end

end

app/views/shared/_accept_friend.html.erb
<% if @user == current_user %>
  <%= link_to 'Accept', connect_friendship_path(friend_id: user), method: :patch, class: "btn btn-success", remote: true %>
  <br/>
  <%= link_to 'Ignore', ignore_friendship_path(friend_id: user), method: :patch, class: "btn btn-info", remote: true %>
<% end %> 

app/views/shared/_add_friend.html.erb
<% if user != current_user %>
  <% if current_user.add_friend?(user) %>
    <%= link_to 'Unfriend', friendship_path(user), method: :delete, class: "btn btn-danger" %>
  <% else%>
    <%= link_to 'Add Friend', friendships_path(friend_id: user), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/shared/_collect.html.erb
<% if @post.collected?(current_user) %>
  <%= link_to 'Uncollect', uncollect_post_path(@post), method: :post, class: "btn btn-warning btn-sm", remote: true %>
<% else %>
  <%= link_to 'Collect', collect_post_path(@post), method: :post, class: "btn btn-primary btn-sm", remote: true %>
<% end %>   

app/views/shared/_post_list.html.erb
    <table class="table table-hover">
      <tbody>
        <% @posts.each do |post| %>
        <tr>
          <th scope="row"><%= post.replies_count %></th>
          <td><%= link_to post.title, post_path(post) %></td>
          <td>
            <% if post.replies.present? %>
            <%= post.replies.last.created_at.to_date %>
            <% end %>
          </td>
          <td><%= post.vieweds_count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    
    <%= paginate @posts %>

app/views/shared/_post_new.html.erb
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_area :description, class: "form-control", rows: "10" %>
      </div>
      <div class="form-group">
        <%= image_tag @post.image, width: '300px' if @post.image? %>
        <%= f.file_field :image %>
      </div>

      Who Can See：
      <div class="form-check form-check-inline">
        <%= f.radio_button :permit, "all", :checked => true, class: "form-check-input" %>
        <label class="form-check-label">All</label>
      </div>
      <div class="form-check form-check-inline">
        <%= f.radio_button :permit, "friend", class: "form-check-input" %>
        <label class="form-check-label">Friend</label>
      </div>
      <div class="form-check form-check-inline">
        <%= f.radio_button :permit, "myself", class: "form-check-input"  %>
        <label class="form-check-label">Myself</label>
      </div> 
      <br/>

      Category：
      <% @categories.each do |category| %>
        <%= fields_for 'categories[]', category do |f| %>
        <div class="form-check form-check-inline">
          <%= f.check_box :category_of_post_ids, checked: @category.include?(category.id) %> 
          <label class="form-check-label"><%= category.name %></label>
        </div>
        <% end %>
      <% end %>
      <br/> 
     <%= f.submit "Save Draft", class: "btn btn-info" %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>

app/views/shared/_user.html.erb
<div class="user-index" >
  <div class="col-md-12">
    <div style="float:left">
     <h4><%= @user.name %></h4>
      <%= image_tag @user.avatar, class: "user-avatar img-thumbnail" if @user.avatar? %>   
      <p><%= @user.introduction %></p>
      <div class="edit-button" style="float:right">
       <%= render partial: "shared/add_friend", locals: {user: @user} %>
      </div>
    <% if @user.email == current_user.email %>
  </div>
      <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-success user-edit-button", style: "float:right" %>
    <% end %>
  </div>
</div>

<ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
  <li class="nav-item"><%= link_to "My Post", posts_user_path, class: "nav-link #{'active' if @posts.present? }" %></li>
  <li class="nav-item"><%= link_to "My Comment", replies_user_path, class: "nav-link #{'active' if @replies.present? }" %></li>
  <li class="nav-item"><%= link_to "My Collect", collects_user_path, class: "nav-link #{'active' if @collects.present? }" %></li>
  <li class="nav-item"><%= link_to "My Draft", drafts_user_path, class: "nav-link #{'active' if @drafts.present? }" %></li>
  <li class="nav-item"><%= link_to "My Friend", friends_user_path, class: "nav-link #{'active' if @friends.present? }" %></li>
</ul>

app/views/shared/_user_info.erb
<% if user.avatar? %>
  <%= link_to user_path(user) do %>
    <%= image_tag user.avatar, width: '100px' ,heitht: '100px', class: "mb-3 img-fluid" %>
  <% end %>
<% end %>
<div>
  <%= link_to user.name, user_path(user) %>
</div>

app/views/shared/_user_post.html.erb
<table class="table table-hover">
  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <th class="text-center"><%= post.title %></th>
      <td class="text-center"><%= post.status %>ed</td>
      <td class="text-center"><%= post.created_at.to_date %></td>
      <% if post.user == current_user %>
      <td><%= link_to "edit", edit_post_path(post) %>
        <%= link_to 'delete', post_path(post), method: :delete, data: { confirm: "Are you sure?"} %>
      </td>
      <% end %>
      <td></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="container">
  <div class="row">
    <div><%= link_to "New Post", new_post_path, class: "btn btn-success"%></div>
  </div>
</div>