config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] do
    # profile/ user page
    member do
      get :posts
      get :replies
      get :collects
      get :drafts
      get :friends
    end
  end

  root "posts#index" 
  resources :posts do
    resources :replies, only: [:create, :destroy, :edit, :update]
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  resources :friendships, only: [:create, :destroy] do
    member do
      patch :ignore
      patch :connect
    end
  end

  resources :categories, only: :show

  namespace :admin do
    resources :categories
    resources :users, only: [:index, :update]
    root "users#index"
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :category_of_posts, dependent: :restrict_with_error
  has_many :posts, through: :category_of_posts
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :set_category, only: [:update, :destroy]

  def index
    @categories = Category.all
    if params[:id]
       set_category
    else
      @category = Category.new
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfully created"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "category was successfully updated"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def destroy
    @category.destroy
    flash[:alert] = "category was successfully deleted"
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @posts = @category.posts.all_publish(current_user).includes(:replies).order(sort_by).page(params[:page]).per(20)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div>
        <%= link_to 'Category List', admin_categories_path, class: "btn btn-default btn-xs" %> |
        <%= link_to 'User List', admin_users_path, class: "btn btn-default btn-xs" %>
      </div>
      <br>

      <table class="table table-hover table-bordered">
        <div class="form-inline" >
          <%= form_for [:admin, @category] do |f| %>
          <div class="form-group">
            <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
          </div>
          <%= f.submit class: "btn btn-primary" %>
          <!-- errors message -->
          <% if @category.errors.any? %>
            <%= @category.errors.full_messages.to_sentence %>
          <% end %>
          <% end %>
        </div>
        <br>

        <thead>
          <tr class="active">
            <th> Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr class="success">
            <th scope="row"><%= category.name %></th>
            <td><%= link_to 'Edit', admin_categories_path(id: category.id) %>
                <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"} %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>