config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] do
    # profile/ user page
    member do
      get :posts
      get :replies
      get :collects
      get :drafts
      get :friends
    end
  end

  root "posts#index" 
  resources :posts do
    resources :replies, only: [:create, :destroy, :edit, :update]
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  resources :friendships, only: [:create, :destroy] do
    member do
      patch :ignore
      patch :connect
    end
  end

  resources :categories, only: :show

  namespace :admin do
    resources :categories
    resources :users, only: [:index, :update]
    root "users#index"
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PhotoUploader
  
  # validates_presence_of :title, :description
  validates_inclusion_of :permit, :in => ["all", "friend", "myself"]
  validates_inclusion_of :status, :in => ["publish", "draft"]

  belongs_to :user

  has_many :category_of_posts, dependent: :destroy
  has_many :categories, through: :category_of_posts

  has_many :replies, dependent: :destroy

  has_many :vieweds, dependent: :destroy

  has_many :collects, dependent: :destroy
  has_many :collected_users, through: :collects, source: :user

  def self.all_publish(user)  # 原本版本有衝突
    where( :status => 'publish', :permit => 'all')
  end

  def self.publishs
    where( :status => 'publish').all
  end 

  def self.drafts
    where( :status => 'draft').all
  end

  def collected? (user)
    self.collected_users.include?(user)
  end

  def last_replied_at
    self.replies.first.created_at.to_date
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  
  def index
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController
  before_action :authenticate_user!, except: :index
  before_action :authenticate_permit_user, only: [:show]

  # GET http://localhost:3000/api/v1/posts
  def index
    @posts = Post.all
    render json: {
      data: @posts
    }
  end
  
   # GET http://localhost:3000/api/v1/posts/:id
  def show
    @post = Post.find_by(id: params[:id])
    if !@post
      render json: {
        message: "Can't find the post!",
        status: 400
      }
    else
      render json: {
      title: @post.title,
      description: @post.description
    }
    end
  end
  
   # POST http://localhost:3000/api/v1/posts/
  def create
    @post = Post.new(post_params)

    if @post.save
      render json: {
        message: "Post was created successfully!",
        result: @post
      }
    else
      render json: {
        errors: @post.errors
      }
    end
  end

  # PATCH http://localhost:3000/api/v1/posts/:id
  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      render json: {
        message: "Post was updated successfully!",
        result: @post
      }
    else
      render json: {
        errors: @post.errors
      }
    end
  end

  # DELETE http://localhost:3000/api/v1/posts/:id
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    render json: {
      message: "Post destroy seccessfully!"
    }
  end
  
  private

  def post_params
    params.permit(:title, :description, :permit, :image, :status)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post, only: [:show, :edit, :update, :destroy, :collect, :uncollect]
  
  def index
    @posts = Post.all_publish(current_user).includes(:replies).order(sort_by).page(params[:page]).per(20)
    @categories = Category.all
  end

  def new
    @post = Post.new
    @categories = Category.all
    @category = @post.categories.ids
  end

  def show
    @user = @post.user
    @reply = Reply.new
    @replies = @post.replies.page(params[:page]).per(20)
    add_view
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if params[:commit] == "Submit"
      @post.status = 'publish'
      if @post.save
        create_categories
        redirect_to post_path(@post)
      else
        render :new
      end
    elsif params[:commit] == "Save Draft"
      @post.status = 'draft'
      if @post.save
        create_categories
        redirect_to drafts_user_path(@post.user)
      else
        render :new
      end
    end
  end

  def edit
    @categories = Category.all
    @category = @post.categories.ids
    unless @post.user == current_user
      redirect_to user_path(@post.user)
    end
  end

  def update
    if params[:commit] == "Submit"
      @post.status = 'publish'
      if @post.update(post_params)
        create_categories
        flash[:notice] = "post was successfully updated"      
        redirect_to post_path(@post)
      else
        flash.now[:alert] = "post was failed to update"
        render :edit
      end
    elsif params[:commit] == "Save Draft"
      if @post.update(post_params)
        create_categories
        flash[:notice] = "draft was successfully updated"      
        redirect_to drafts_user_path(@post.user)
      else
        flash.now[:alert] = "draft was failed to update"
        render :edit
      end
    end
  end

  def destroy
    if @post.status == 'draft'
      @post.destroy
      redirect_to drafts_user_path(current_user)
      flash[:alert] = "draft was deleted"  
    else   
      @post.destroy
      redirect_to user_path(current_user)
      flash[:alert] = "post was deleted"
    end
  end

   def collect
    collect = Collect.create(user: current_user, post: @post)
    if collect.save
      flash[:notice] = "Successfully collected"
    else
      flash[:alert] = collect.errors.full_messages.to_sentence if collect.errors.any?
      redirect_back(fallback_location: root_path)
    end
  end

  def uncollect
    collect = @post.collects.find_by(user: current_user)
    if collect.destroy
      flash[:notice] = "Successfully Uncollect"
    else
      flash[:alert] = "Error"
      redirect_back(fallback_location: root_path)
    end
  end

  def feeds
    @users_count = User.all.size
    @post_count = Post.publishs.size
    @replies_count = Reply.all.size
    @popular_posts = Post.publishs.order(replies_count: :desc).limit(10)
    @chatterbox_user = User.left_joins(:replies).group(:id).order('COUNT(replies.id) DESC').limit(10)
  end

 
  private

  def add_view 
    Viewed.create(post: @post, user: current_user)
  end


  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :permit, :image)
  end

  def create_categories
    if params["categories"].present?
      params["categories"].each do |key, value|
        if value == {"category_of_post_ids"=>"1"}
          @post.category_of_posts.create(category_id: key)
        end
      end
    end
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/collect.js.erb
var collect = document.createElement("div");
  collect.id = "collect-<%= @post.id %>";
  collect.innerHTML = "<%= j render(:partial => "shared/collect") %>";
  $("div#collect-<%= @post.id %>").html(collect);

app/views/posts/edit.html.erb
<%= render partial: "shared/post_new" %>

app/views/posts/feeds.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="info"  style="text-align: center;">
        <div class="col-md-4" >
          <h3>User</h3>
          <h4><%= @users_count %></h4>
        </div>
        <div class="col-md-4">
          <h3>Post</h3>
          <h4><%= @post_count %></h4>
        </div>
        <div class="col-md-4">
          <h3>Comment</h3>
          <h4><%= @replies_count %></h4> 
        </div>
      </div>
    </div>
  </div>
</div>
<br/>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <table class="table table-hover">
        <thead>
          <tr>
            <h2 class="text-center">Chatterbox</h2>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @chatterbox_user.each_with_index do |user,index| %>
            <th scope="row"><%= index +1 %></th>
            <td><%= user.name %></td>
            <td><%= user.replies.size %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<hr/>

<div class="container">
  <div class="col-6">
    <table class="table table-hover">
      <thead>
        <tr>
          <h2 class="text-center">Most Popular Post</h2>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% @popular_posts.each_with_index do |post,index| %>
          <th scope="row"><%= index +1 %></th>
          <td><%= post.title %></td>
          <td><%= post.created_at.to_date %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/posts/index.html.erb
<div class="post-index" >
  <div class="col-md-12">
    <h1>Dojo Forum</h1>       
  </div>
</div>

<div class="container">
  <div class="row">
    <ul class="nav nav-pills">
      <li class="nav-item"><%= link_to "All", root_path, class: "nav-link" %></li>
      <% @categories.each do |category| %>
      <li class="nav-item"><%= link_to category.name, category_path(category), class: "nav-link" %></li>
      <% end %>
    </ul>  
    <br>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col"><%= link_to 'Replies count', posts_path( :order => "replies_count") %></th>
          <th scope="col">Title</th>
          <th scope="col"><%= link_to 'Last replied at', posts_path( :order => "last_replied_at") %></th>
          <th scope="col"><%= link_to 'Viewed count', posts_path( :order => "vieweds_count") %></th>
        </tr>
      </thead>
      <%= render partial: "shared/post_list" %>
    </table>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/post_new" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h3><%= @post.title %></h3>
      <div id="collect-<%= @post.id %>" class="float-right collect-btn"> 
        <%= render partial: "shared/collect", :locals => { :post => @post } %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-6 col-md-3">
      <%= link_to user_path(@user) do %>
        <%= image_tag @user.avatar, class: "user-avatar img-thumbnail" if @user.avatar? %>
        <h4 class="text-center"><%= @user.name %></h4>
      <% end %>
      <div class="add-friend">
        <%= render partial: "shared/add_friend", locals: {user: @user} %>
      </div>
    </div>
    <div class="col-12 col-sm-6 col-md-9">
      <%= image_tag @post.image, class: "post-image img-thumbnail" if @post.image? %>
      <p><%= @post.description %></p>
      <div class="clearfix">
        <% if current_user.admin? %>
        <%= link_to "Delete", post_path(@post), class: "btn btn-danger float-right", method: :delete, data: { confirm: "Are you sure?"} %>
        <% end %>
        <% if @user == current_user %>
        <%= link_to 'delete', post_path(@post), class: "btn float-right", method: :delete, data: { confirm: "Are you sure?"} %>
        <%= link_to "edit", edit_post_path(@post), class: "btn float-right" %>
        <% end %>        
      </div>
    </div>
  </div>
</div>
<hr>
<div class="container">
  <div class="row">
    <% @replies.each do |reply| %>
    <div class="col-6 col-md-3">
      <%= link_to user_path(reply.user) do %>
        <%= image_tag reply.user.avatar, class: "user-avatar img-thumbnail" if reply.user.avatar? %>      
        <h4 class="text-center"><%= reply.user.name %></h4>
      <% end %>
      <div class="add-friend">
        <%= render partial: "shared/add_friend", locals: {user: reply.user} %>
      </div>  
    </div>
    <div id="<%= reply.id %>" class="col-12 col-sm-6 col-md-9">
      <div class="reply-form">
        <div class="body">
          <%= simple_format reply.comment %>
          <% if reply.user == current_user %>
          <%= link_to "Delete", post_reply_path(@post, reply), class: "btn float-right", method: :delete, data: { confirm: "Are you sure?"} %>
          <%= link_to "Edit", edit_post_reply_path(@post, reply), class: "btn float-right", remote: true %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
    <div class="col-md-12">
      <%= form_for [@post, @reply] do |f| %>
      <div class="form-group">
        <%= f.text_area :comment, placeholder: "add comment", class: "form-control", rows: "8" %>
      </div>
      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
    <%= paginate @replies %>
  </div>
</div>

app/views/posts/uncollect.js.erb
var uncollect = document.createElement("div");
  uncollect.id = "collect-<%= @post.id %>";
  uncollect.innerHTML = "<%= j render(:partial => "shared/collect") %>";
  $("div#collect-<%= @post.id %>").html(uncollect);