config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] do
    # profile/ user page
    member do
      get :posts
      get :replies
      get :collects
      get :drafts
      get :friends
    end
  end

  root "posts#index" 
  resources :posts do
    resources :replies, only: [:create, :destroy, :edit, :update]
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  resources :friendships, only: [:create, :destroy] do
    member do
      patch :ignore
      patch :connect
    end
  end

  resources :categories, only: :show

  namespace :admin do
    resources :categories
    resources :users, only: [:index, :update]
    root "users#index"
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DojoForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar " style="background-color: #dbeda9;">
      <div class="container-fluid">
        <%= link_to "首頁", root_path, class: "navbar-brand" %>
        <ul class="pull-left nav navbar-nav">
          <li>
            <p class="navbar-text"><%= link_to "Feeds", feeds_posts_path %></p>
          </li>
          <li>
            <p class="navbar-text"><%= link_to "All Post", root_path %></p>
          </li>
          <li>
            <p class="navbar-text"><%= link_to "New Post", new_post_path %></p>
          </li>
        </ul>
        <ul class="pull-right text-right nav navbar-nav">
        <% if current_user %>
        Hi, <%= current_user.email %>
        <% if current_user.admin? %>
          <li><%= link_to 'Admin後台', admin_users_path %></li>
        <% end %>
          <li><%= link_to 'Profile', user_path(current_user) %></li>
        <%= link_to('Log out', destroy_user_session_path, method: :delete) %> |
        <%= link_to('修改密碼', edit_user_registration_path) %>
        <% else %>
        <%= link_to('Sign up', new_user_registration_path) %> |
        <%= link_to('Log in', new_user_session_path) %>
        <% end %>
      </ul>
    </div>
    </nav>

    <% if current_user %>
      <p class="pull-right">你的 API Token：<code><%= current_user.authentication_token  %></code></p>
    <% end %>
    
    <% if flash[:notice] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      </div>
    </div>
    <% end %>

    <%= yield %>
  </body>
</html>